server:
  port: 8081

spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
            - id: datamanager-route
              uri: lb://DATAMANAGER 
              predicates:
                - Path=/datamanager/**
              filters:
                - StripPrefix=1
            - id: servicetest-route
              uri: lb://SERVICETEST
              predicates:
                -Path=/servicetest/**
              filters:
                -StripPrefix=1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway.mvc: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    com.netflix.discovery: DEBUG
