server:
  port: 8081

spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: servicetest
            uri: lb://servicetest
            predicates:
              - name: Path
                args:
                  pattern: /api/servicetest/**
            filters:
              - name: StripPrefix
                args:
                  parts: 2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
