server:
  port: 8081

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          # Remove the filters from here - they apply to all routes
      routes:
        - id: datamanager-route
          uri: lb://datamanager
          predicates:
            - Path=/datamanager/**
          filters:
            - StripPrefix=1
        # Add explicit route for better control
        - id: datamanager-direct
          uri: lb://datamanager
          predicates:
            - Path=/api/datamanager/**
          filters:
            - StripPrefix=2
          
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway.discovery: DEBUG
